## Setup

### Import Libraries

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Tensors in Pytorch

Tensors are a generalized formulation to higher dimensions of mathematical objects that we are/may be familiar with from linear algebra: scalars, vectors, and matrices. A scalar is a 0D-tensor, a vector is a 1D-tensor, and a matrix is a 2D-tensor. Tensors can have any N number of dimensions.

Tensors are more than just a container for data, though, they also include information about the linear transformations between tensors.

Pytorch is a library that is used instead of NumPy when working with data in Deep Learning, but it's often used in the same way as NumPy. It's also optimized to utilize the power of GPUs.

Tensors can be constructed from standard python data collections like lists, tuples, and arrays.

In [2]:
# tensor from a list
a = torch.tensor([0,1,2])
a

tensor([0, 1, 2])

In [3]:
# tensor from tuples
b = ((1.0,1.1), (1.2, 1.3))
b = torch.tensor(b)
b

tensor([[1.0000, 1.1000],
        [1.2000, 1.3000]])

In [4]:
# tensor of from numpy array
c = np.ones([2,3])
c = torch.tensor(c)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Pytorch also provides functions to initialize arrays, like NumPy.

In [5]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [6]:
b = torch.zeros(4)
b

tensor([0., 0., 0., 0.])

In [15]:
c = torch.rand(size = (5, 2))
c

tensor([[0.7454, 0.1705],
        [0.3637, 0.8468],
        [0.1040, 0.1609],
        [0.8851, 0.5557],
        [0.7545, 0.7310]])

In [14]:
d = torch.randn(size = (3,4))
d

tensor([[-0.2849,  2.3816, -0.9405,  0.2406],
        [-2.2642, -0.5441, -0.0320, -1.0287],
        [-0.9932, -0.1222,  0.6081,  1.2346]])

Set seed in torch

In [24]:
torch.manual_seed(0)

# now we get the same number every time (as long as torch.manual_seed(0) has been run again)
torch.randn(1)

tensor([1.5410])

#### arange and linspace

In [26]:
torch.arange(0,10,step=1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
torch.linspace(0,5,steps=11)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000])

### Tensor Operations

Mathematical operations can be performed on tensors both using built-in python operators and methods in pytorch.

In [42]:
a = torch.ones(5)
b = torch.zeros(5)+0.1

a, b

(tensor([1., 1., 1., 1., 1.]),
 tensor([0.1000, 0.1000, 0.1000, 0.1000, 0.1000]))

In [43]:
c = a+b
c

tensor([1.1000, 1.1000, 1.1000, 1.1000, 1.1000])

In [44]:
# note that an out parameter can be used to create a variable that contains the result
torch.add(a, b, out=c)
c

tensor([1.1000, 1.1000, 1.1000, 1.1000, 1.1000])

In [45]:
torch.multiply(a,b,out=d)
d

tensor([0.1000, 0.1000, 0.1000, 0.1000, 0.1000])

### Arithmetic operations

In [52]:
a = torch.tensor([[1,2,3], [4,5,6]], dtype=float)
a.mean(), a.mean(axis=0), a.mean(axis=1)

(tensor(3.5000, dtype=torch.float64),
 tensor([2.5000, 3.5000, 4.5000], dtype=torch.float64),
 tensor([2., 5.], dtype=torch.float64))

In [53]:
a.sum(), a.sum(axis=0), a.sum(axis=1)

(tensor(21., dtype=torch.float64),
 tensor([5., 7., 9.], dtype=torch.float64),
 tensor([ 6., 15.], dtype=torch.float64))

### Matrix Operations

The @ symbol or `torch.matmul()` can be used to multiply tensors. ``torch.dot()`` can only be used for 1D tensors (vectors). For transposing tenosrs, use ``Tensor.T`` or ``torch.t()``.

In [71]:
A = torch.tensor([[1,2],[3,4]])

B = torch.tensor([[1,1], [0,0]])

A, B

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 0],
         [1, 0]]))

In [72]:
C1 = A @ B

C2 = torch.matmul(input = A, other= B)

C1, C2

(tensor([[1, 1],
         [3, 3]]),
 tensor([[1, 1],
         [3, 3]]))

In [76]:
# elementwise multiplication of matrices

D = torch.mul(A, B)
D

tensor([[1, 2],
        [0, 0]])