## Setup

### Import Libraries

In [91]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Tensors in Pytorch

Tensors are a generalized formulation to higher dimensions of mathematical objects that we are/may be familiar with from linear algebra: scalars, vectors, and matrices. A scalar is a 0D-tensor, a vector is a 1D-tensor, and a matrix is a 2D-tensor. Tensors can have any N number of dimensions.

Tensors are more than just a container for data, though, they also include information about the linear transformations between tensors.

Pytorch is a library that is used instead of NumPy when working with data in Deep Learning, but it's often used in the same way as NumPy. It's also optimized to utilize the power of GPUs.

Tensors can be constructed from standard python data collections like lists, tuples, and arrays.

In [92]:
# tensor from a list
a = torch.tensor([0,1,2])
a

tensor([0, 1, 2])

In [93]:
# tensor from tuples
b = ((1.0,1.1), (1.2, 1.3))
b = torch.tensor(b)
b

tensor([[1.0000, 1.1000],
        [1.2000, 1.3000]])

In [94]:
# tensor of from numpy array
c = np.ones([2,3])
c = torch.tensor(c)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Pytorch also provides functions to initialize arrays, like NumPy.

In [95]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [96]:
b = torch.zeros(4)
b

tensor([0., 0., 0., 0.])

In [97]:
c = torch.rand(size = (5, 2))
c

tensor([[0.0223, 0.1689],
        [0.2939, 0.5185],
        [0.6977, 0.8000],
        [0.1610, 0.2823],
        [0.6816, 0.9152]])

In [98]:
d = torch.randn(size = (3,4))
d

tensor([[ 0.4159,  0.8396, -0.8265, -0.7949],
        [-0.9528,  0.3717,  0.4087,  1.4214],
        [ 0.1494, -0.6709, -0.2142, -0.4320]])

Set seed in torch

In [99]:
torch.manual_seed(0)

# now we get the same number every time (as long as torch.manual_seed(0) has been run again)
torch.randn(1)

tensor([1.5410])

#### arange and linspace

In [100]:
torch.arange(0,10,step=1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
torch.linspace(0,5,steps=11)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000])

### Tensor Operations

Mathematical operations can be performed on tensors both using built-in python operators and methods in pytorch.

In [102]:
a = torch.ones(5)
b = torch.zeros(5)+0.1

a, b

(tensor([1., 1., 1., 1., 1.]),
 tensor([0.1000, 0.1000, 0.1000, 0.1000, 0.1000]))

In [103]:
c = a+b
c

tensor([1.1000, 1.1000, 1.1000, 1.1000, 1.1000])

In [104]:
# note that an out parameter can be used to create a variable that contains the result
torch.add(a, b, out=c)
c

tensor([1.1000, 1.1000, 1.1000, 1.1000, 1.1000])

In [105]:
torch.multiply(a,b,out=d)
d

C:\Users\atle_\AppData\Local\Temp\ipykernel_26972\3231070935.py:1: UserWarning: An output with one or more elements was resized since it had shape [3, 4], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\bld\libtorch_1753839225953\work\aten\src\ATen\native\Resize.cpp:37.)
  torch.multiply(a,b,out=d)


tensor([0.1000, 0.1000, 0.1000, 0.1000, 0.1000])

### Arithmetic operations

In [106]:
a = torch.tensor([[1,2,3], [4,5,6]], dtype=float)
a.mean(), a.mean(axis=0), a.mean(axis=1)

(tensor(3.5000, dtype=torch.float64),
 tensor([2.5000, 3.5000, 4.5000], dtype=torch.float64),
 tensor([2., 5.], dtype=torch.float64))

In [107]:
a.sum(), a.sum(axis=0), a.sum(axis=1)

(tensor(21., dtype=torch.float64),
 tensor([5., 7., 9.], dtype=torch.float64),
 tensor([ 6., 15.], dtype=torch.float64))

### Matrix Operations

The @ symbol or `torch.matmul()` can be used to multiply tensors. ``torch.dot()`` can only be used for 1D tensors (vectors). For transposing tenosrs, use ``Tensor.T`` or ``torch.t()``.

In [108]:
A = torch.tensor([[1,2],[3,4]])

B = torch.tensor([[1,1], [0,0]])

A, B

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 1],
         [0, 0]]))

In [109]:
C1 = A @ B

C2 = torch.matmul(input = A, other= B)

C1, C2

(tensor([[1, 1],
         [3, 3]]),
 tensor([[1, 1],
         [3, 3]]))

In [110]:
# elementwise multiplication of matrices
D = torch.mul(A, B)
D

tensor([[1, 2],
        [0, 0]])

#### Conversion to other Python objects

Converting to numpy will "break the graph". In other words, autograd, which is a core feature of pytorch, won't be supported any more.


In [ ]:
x = torch.tensor([1,2,3])
x.numpy()

array([1, 2, 3])

In [112]:
x = torch.tensor([2.44])
x.item(), float(x), int(x)

(2.440000057220459, 2.440000057220459, 2)

Tensors come with functions to do backward propagation and provides the gradients in the graph.

In [115]:
x = torch.tensor([1,2,3], dtype=float, requires_grad=True)

# simulates forward propagation
x_sum = x.sum()
x_sum

tensor(6., dtype=torch.float64, grad_fn=<SumBackward0>)

In [ ]:
x_sum.backward()

In [117]:
x.grad

tensor([1., 1., 1.], dtype=torch.float64)

TODO: Create a more advanced computational graph, do forward and backward propagation, and get the gradients.

#### Device

As mentioned, Pytorch is optimized for use on GPUs. When constructing a tensor, there's a parameter `device` that can be used to set the device to be used to CPUs or GPUs. By default, device is set to CPU.

In [83]:
# check the device of the tensor x
x = torch.tensor([1,2,3])
x.device

device(type='cpu')

In [88]:
x = torch.tensor([1,2,3], device = 'cpu')
x.device

device(type='cpu')

To use GPUs, set device to "cuda". This will only work if you have GPUs on a laptop, if you use a cloud service that offers GPU hours like google colab or kaggle, or if you run your code on a cluster.

In [89]:
# this will produce an error
x = torch.tensor([1,2,3], device = 'cuda')
x.device

AssertionError: Torch not compiled with CUDA enabled